user.auth=false
jemboss.server=false
server.public=https://jemboss.hgmp.mrc.ac.uk:8443/axis/services
server.private=https://jemboss.hgmp.mrc.ac.uk:8443/axis/services
service.public=JembossAuthServer
service.private=JembossAuthServer
embossData=/workspaces/hasna/venv/share/EMBOSS/data/
embossBin=/workspaces/hasna/venv/bin/
embossPath=/usr/bin:/bin:/packages/clustal/:/packages/primer3/bin:/data/jobqueue/bin/:/usr/ucb/
acdDirToParse=/workspaces/hasna/venv/share/EMBOSS/acd/
embossURL=http://emboss.sourceforge.net/
